# Generated by Django 6.0.1 on 2026-02-05 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_layawayimage'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayawayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rwf', models.PositiveIntegerField(help_text='Amount paid in RWF')),
                ('reference', models.CharField(blank=True, help_text='Optional transaction reference (e.g. Mobile Money code)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_layaway_payments', to=settings.AUTH_USER_MODEL)),
                ('layaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.layaway')),
            ],
            options={
                'verbose_name': 'Layaway payment',
                'verbose_name_plural': 'Layaway payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
