# Generated by Django 6.0.1 on 2026-01-29 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="Price in RWF (Rwandan Francs)"
                    ),
                ),
                (
                    "max_order_price",
                    models.PositiveIntegerField(help_text="Maximum order price in RWF"),
                ),
                ("description", models.TextField(max_length=400)),
                ("is_available", models.BooleanField(default=True)),
                ("duration_days", models.PositiveIntegerField(default=365)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("paid", "Payment Received"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mobile_money", "Mobile Money"),
                            ("cash", "Cash"),
                            ("bank", "Bank Transfer"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Mobile Money Tx ID, Bank slip number, or receipt reference",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "amount_paid",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Amount paid in RWF (Rwandan Francs)",
                        null=True,
                    ),
                ),
                ("payment_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_memberships",
                        to="memberships.membership",
                    ),
                ),
                (
                    "payment_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="idx_membership_user"),
                    models.Index(fields=["status"], name="idx_membership_status"),
                    models.Index(fields=["user", "status"], name="idx_user_status"),
                    models.Index(
                        fields=["status", "end_date"], name="idx_status_end_date"
                    ),
                    models.Index(
                        fields=["payment_reference"], name="idx_payment_reference"
                    ),
                    models.Index(fields=["payment_mode"], name="idx_payment_mode"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("user", "membership"),
                        name="unique_pending_membership",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("user",),
                        name="unique_active_membership_per_user",
                    ),
                ],
            },
        ),
    ]
