# Generated by Django 6.0.1 on 2026-02-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0003_alter_membership_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="max_order_price",
            field=models.PositiveIntegerField(
                help_text="Maximum layaway (item value) in RWF for this tier; used for eligibility."
            ),
        ),
    ]
