# Generated by Django 6.0.1 on 2026-02-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="layaway",
            name="seller_address",
            field=models.CharField(
                blank=True,
                help_text="Seller/shop address (district, sector, street, etc.)",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="layaway",
            name="seller_name",
            field=models.CharField(
                blank=True, help_text="Seller or shop name (optional)", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="layaway",
            name="seller_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
