# Generated by Django 6.0.1 on 2026-02-05 13:47

import apps.orders.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_layaway_seller_address_layaway_seller_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayawayImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Photo or screenshot of the requested item",
                        upload_to=apps.orders.models.layaway_item_image_upload_to,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=150)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Display order (lower first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "layaway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_images",
                        to="orders.layaway",
                    ),
                ),
            ],
            options={
                "verbose_name": "Layaway item image",
                "verbose_name_plural": "Layaway item images",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
