# Generated by Django 6.0.1 on 2026-02-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_member_profile_and_measurements"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="address_notes",
            field=models.CharField(
                blank=True,
                help_text="Additional address details (landmark, building, etc.)",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="alternate_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="cell",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="house_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="sector",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="street",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="village",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
